name: Compile C++ code
on: [push]
jobs:
  Compile-Code:
    name: Compile Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup-gcc
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: compile-somecode
      
      run: |
        pwd
        ls
        cd ..
        pwd 
        ls
        gcc somecode.cpp -o somecode.out
    - name: commit and push
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
